// Generated by Wrangler on Tue Feb 25 2025 15:57:34 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface WorkerEnv`

interface WorkerEnv {
  DB: D1Database;
  ENVIRONMENT: "development" | "staging" | "production";
  CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
}
