// Generated by Wrangler on Tue May 21 2024 15:57:34 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface WorkerEnv`

interface WorkerEnv {
  BENCHMARK_URL: string;
  STATS_DB: D1Database;
  BENCHMARK_DO: DurableObjectNamespace<
    import("./src/benchmark-do").BenchmarkDurableObject
  >;
}
